name: abelo-host
services:
  nginx:
    container_name: abelo-host-nginx
    hostname: nginx
    image: nginx:alpine
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
      - source: nginx-site-config
        target: /etc/nginx/templates/default.conf.template
    volumes:
      - .:/app
    working_dir: /app
    environment:
      TZ: Europe/Minsk
    ports:
      - ${DOCKER_SITE_PORT:-80}:80
    depends_on:
      - php

  php:
    container_name: abelo-host-php
    hostname: php
    image: abelo-host/php-fpm
    build:
      context: ./docker/php
      args:
        USER_UID: ${DOCKER_UID:-1000}
        USER_GID: ${DOCKER_GID:-1000}
    configs:
      - source: php-config
        target: /usr/local/etc/php/conf.d/custom.ini
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PHP_IDE_CONFIG: serverName=abelo-host
      XDEBUG_TRIGGER: true
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db

  db:
    container_name: abelo-host-db
    hostname: db
    image: mysql:9
    configs:
      - source: db-config
        target: /etc/mysql/conf.d/custom.cnf
    volumes:
      - db:/var/lib/mysql
    environment:
      TZ: Europe/Minsk
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - ${DOCKER_DB_PORT:-3306}:3306

volumes:
  db:
    name: abelo-host-db

configs:
  nginx-config:
    file: ./docker/nginx/nginx.conf
  nginx-site-config:
    file: ./docker/nginx/site.conf
  php-config:
    file: ./docker/php/php.conf
  db-config:
    file: ./docker/db/mysql.conf

networks:
  default:
    name: abelo-host-network
